from typing import List, Annotated, TypedDict
import operator

# Define the data structure for a single paper/artifact
class Artifact(TypedDict):
    id: str
    title: str
    summary: str
    authors: List[str]
    published_date: str
    source_url: str
    category: str
    source_type: str           # <--- NEW: 'arxiv', 'github', or 'hackernews'
    score: int = 0             # Assigned by Gatekeeper (0-10)
    relevance_reason: str = "" # Why Gatekeeper picked it
    technical_depth: str = ""  # Assigned by Analyst
    code_link: str = ""        # GitHub link if found

# The Graph State
class AgentState(TypedDict):
    # The 'inbox' of raw items found by the Monitor
    # operator.add ensures that if we run multiple monitors, lists merge rather than overwrite
    raw_artifacts: Annotated[List[Artifact], operator.add] 
    
    # Items that passed the Gatekeeper's filter
    screened_artifacts: Annotated[List[Artifact], operator.add]
    
    # Final reports generated by the Journalist
    final_digest: str
    
    # Loop control (to prevent infinite retries/hallucination loops)
    iteration_count: int